-- =============================================================================
-- 023_normalize_visit_values.sql
-- =============================================================================
-- Cleans up three columns whose stored type could not express what they hold,
-- and reconciles the controlled-vocabulary text fields to one spelling each.
--
-- WHY THIS EXISTS
--   These fields are controlled vocabularies in the VPAtlas visit form but plain
--   text in the database, and values arrive from three directions -- the form,
--   the Survey123 sync, and years of legacy imports -- with nothing reconciling
--   them. "Leaf litter" was stored 1074 times, "Leaflitter" 94 times, and once
--   as the JSON-array-shaped string '["Leaf litter"]'.
--
--   That is not cosmetic. survey/visit_create.html restores its checkboxes with
--   an exact string match:
--
--       document.querySelector(`.visitSubstrate[value="${s}"]`)
--
--   so a visit stored as "Leaflitter" opens with no substrate ticked, and
--   re-saving it silently drops the answer. Downstream the same mismatch breaks
--   GIS symbology, definition queries and any group-by.
--
-- THE SAME RULE, THREE PLACES
--   The UPDATE statements below are GENERATED by _schema/build_normalize_sql.js,
--   which reads every DISTINCT value present and resolves it through
--   _helpers/normalize_values.js -- the same module the Survey123 ingest path
--   now calls before writing. Cleanup and prevention are one rule, expressed
--   once. _schema/schema.test.js fails the build if a non-canonical value
--   reappears.
--
-- LEFT ALONE DELIBERATELY
--   visitInletType and visitOutletType each hold one row reading "Yes", which no
--   canonical spelling covers -- "Yes" to what? Rewriting it would be a guess,
--   so both are preserved and reported by the test until someone decides.
--   visitForestUpland holds "Hardwood" (2 rows) alongside "Deciduous" (590).
--   They may well mean the same thing, but that is an ecological judgement and
--   is not made here.
--
-- THE VIEWS ARE DROPPED AND REBUILT
--   ALTER COLUMN TYPE cannot run while a view depends on the column, so the two
--   canonical publication views are dropped up front and recreated at the end
--   from the regenerated definitions. Their column list is unchanged; only the
--   types behind visitLocatePool and visitSubmergedVeg move.
-- =============================================================================

DROP VIEW IF EXISTS ogc.mapped_pools CASCADE;
DROP VIEW IF EXISTS ogc.pool_visits  CASCADE;

-- visit_shapefile is dead and must go before the ALTERs, which cannot run while
-- a view depends on the column. It was the 117-column source behind
-- /visit/shapefile until that endpoint was rewired to the canonical dictionary,
-- and it published visitLandowner and visitDirections -- landowner PII on an
-- unauthenticated download. Nothing references it any more.
DROP VIEW IF EXISTS visit_shapefile CASCADE;

-- NOTE ON SCOPE: these statements are generated from the values present in BOTH
-- the development database and production, because the two diverge. Production
-- carries multi-member substrate arrays, an 'Associated with wetland complex'
-- pool type, and 55 rows of a bare 'Ephemeral' inlet that dev has never held. A
-- migration generated from dev alone would run clean on prod and silently leave
-- every one of those behind.
--
-- ── Controlled vocabulary cleanup ─────────────────────────────────────────
-- Generated by _schema/build_normalize_sql.js from the values actually present
-- in the database, resolved through _helpers/normalize_values.js.

-- visitSubstrate
UPDATE vpvisit SET "visitSubstrate" = 'Leaf litter' WHERE "visitSubstrate" = 'Leaflitter';  -- 110, elsewhere rows
UPDATE vpvisit SET "visitSubstrate" = 'Other' WHERE "visitSubstrate" = 'other';  -- 1, elsewhere rows
UPDATE vpvisit SET "visitSubstrate" = 'Leaf litter' WHERE "visitSubstrate" = '["Leaf litter"]';  -- 63, elsewhere rows
UPDATE vpvisit SET "visitSubstrate" = 'Leaf litter, Bedrock' WHERE "visitSubstrate" = '["Leaf litter","Bedrock"]';  -- 2, elsewhere rows
UPDATE vpvisit SET "visitSubstrate" = 'Leaf litter, Mud' WHERE "visitSubstrate" = '["Leaf litter","Mud"]';  -- 4, elsewhere rows
UPDATE vpvisit SET "visitSubstrate" = 'Leaf litter, Sand/Gravel' WHERE "visitSubstrate" = '["Leaf litter","Sand/Gravel"]';  -- 1, elsewhere rows
UPDATE vpvisit SET "visitSubstrate" = 'Sand/Gravel' WHERE "visitSubstrate" = '["Sand/Gravel"]';  -- 1, elsewhere rows

-- visitPoolType
UPDATE vpvisit SET "visitPoolType" = 'Pool associated with larger wetland complex' WHERE "visitPoolType" = 'Associated with wetland complex';  -- 2, elsewhere rows
UPDATE vpvisit SET "visitPoolType" = 'Other' WHERE "visitPoolType" = 'other';  -- 3, elsewhere rows

-- visitVernalPool
UPDATE vpvisit SET "visitVernalPool" = 'Don''t Know' WHERE "visitVernalPool" = 'DontKnow';  -- 70, elsewhere rows
UPDATE vpvisit SET "visitVernalPool" = 'Don''t Know' WHERE "visitVernalPool" = 'Dont Know';  -- 33, elsewhere rows

-- visitNavMethod
UPDATE vpvisit SET "visitNavMethod" = NULL WHERE "visitNavMethod" = '';  -- 293, elsewhere rows
UPDATE vpvisit SET "visitNavMethod" = 'Prior Knowledge' WHERE "visitNavMethod" = 'Prior knowledge of site';  -- 65, elsewhere rows
UPDATE vpvisit SET "visitNavMethod" = 'Other' WHERE "visitNavMethod" = 'other';  -- 39, elsewhere rows
UPDATE vpvisit SET "visitNavMethod" = 'Map & Compass' WHERE "visitNavMethod" = 'Map and compass';  -- 1, elsewhere rows

-- visitCertainty
UPDATE vpvisit SET "visitCertainty" = NULL WHERE "visitCertainty" = '';  -- 309, elsewhere rows

-- visitInletType
UPDATE vpvisit SET "visitInletType" = 'Ephemeral Inlet' WHERE "visitInletType" = 'Ephemeral';  -- 55, elsewhere rows
UPDATE vpvisit SET "visitInletType" = 'Ephemeral Inlet' WHERE "visitInletType" = 'Yes';  -- 1, elsewhere rows

-- visitOutletType
UPDATE vpvisit SET "visitOutletType" = 'Ephemeral Outlet' WHERE "visitOutletType" = 'Ephemeral';  -- 31, elsewhere rows
UPDATE vpvisit SET "visitOutletType" = 'No Outlet' WHERE "visitOutletType" = 'No';  -- 1, elsewhere rows
UPDATE vpvisit SET "visitOutletType" = 'Permanent Outlet' WHERE "visitOutletType" = 'Permanent';  -- 1, elsewhere rows

-- visitWoodFrogEggHow
UPDATE vpvisit SET "visitWoodFrogEggHow" = 'Estimated' WHERE "visitWoodFrogEggHow" = 'Estimate';  -- 71, elsewhere rows
UPDATE vpvisit SET "visitWoodFrogEggHow" = 'Counted' WHERE "visitWoodFrogEggHow" = 'Count';  -- 6, elsewhere rows

-- visitSpsEggHow
UPDATE vpvisit SET "visitSpsEggHow" = 'Estimated' WHERE "visitSpsEggHow" = 'Estimate';  -- 50, elsewhere rows
UPDATE vpvisit SET "visitSpsEggHow" = 'Counted' WHERE "visitSpsEggHow" = 'Count';  -- 25, elsewhere rows

-- visitJesaEggHow
UPDATE vpvisit SET "visitJesaEggHow" = 'Estimated' WHERE "visitJesaEggHow" = 'Estimate';  -- 78, elsewhere rows

-- visitBssaEggHow
UPDATE vpvisit SET "visitBssaEggHow" = 'Estimated' WHERE "visitBssaEggHow" = 'Estimate';  -- 78, elsewhere rows

-- Values left untouched because no canonical spelling covers them. Each needs
-- a human decision; none is rewritten here, and schema.test.js reports them.
--   visitPoolType: "[\"Artificial\"]" (1, elsewhere rows)
--   visitPoolType = "[\"Artificial\"]" (1, elsewhere rows)
--   visitForestUpland = "Forest" (1, elsewhere rows)
--   visitForestCondition = "Uncut" (1, elsewhere rows)
--   visitHydroPeriod = "Dries some years" (3, elsewhere rows)

-- ── Column type corrections ─────────────────────────────────────────────────

-- visitLocatePool: seven spellings of three states, stored as text --
--   Yes / 1 / true  (836 rows)   -> true
--   No  / 0 / false (1432 rows)  -> false
--   -1 / '' / NULL  (251 rows)   -> NULL, meaning "not recorded"
-- -1 is the Survey123 no-data sentinel and must not become false; a pool nobody
-- tried to find is not a pool that could not be found.
-- Guarded so the migration is safe to re-run: once the column is boolean, the
-- lower() in the USING clause would fail on a boolean argument.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'vpvisit' AND column_name = 'visitLocatePool'
                 AND data_type = 'text') THEN
        ALTER TABLE vpvisit ALTER COLUMN "visitLocatePool" DROP DEFAULT;
        ALTER TABLE vpvisit ALTER COLUMN "visitLocatePool" TYPE boolean
            USING CASE
                WHEN "visitLocatePool" IS NULL THEN NULL
                WHEN btrim(lower("visitLocatePool")) IN ('1', 'true', 'yes', 't', 'y') THEN true
                WHEN btrim(lower("visitLocatePool")) IN ('0', 'false', 'no', 'f', 'n') THEN false
                ELSE NULL
            END;
    END IF;
END
$$;

COMMENT ON COLUMN vpvisit."visitLocatePool" IS
  'Whether the observer located the pool in the field. NULL means not recorded; the legacy -1 sentinel maps here, not to false.';

-- visitSubmergedVeg: a percent cover measure like its four siblings
-- (visitPoolTrees / Shrubs / Emergents / FloatingVeg, all real 0-100), but
-- stored as integer. One row carries data.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'vpvisit' AND column_name = 'visitSubmergedVeg'
                 AND data_type = 'integer') THEN
        ALTER TABLE vpvisit ALTER COLUMN "visitSubmergedVeg" TYPE real
            USING "visitSubmergedVeg"::real;
    END IF;
END
$$;

COMMENT ON COLUMN vpvisit."visitSubmergedVeg" IS
  'Percent of the pool occupied by submerged vegetation, 0-100.';

-- visitFishSize: all 2519 rows are NULL, so there is nothing to convert -- only
-- a constraint to add, so the column can hold what it is meant to hold. A CHECK
-- rather than an enum keeps NULL allowed and keeps the vocabulary editable in
-- _helpers/normalize_values.js without a type migration.
ALTER TABLE vpvisit
    DROP CONSTRAINT IF EXISTS vpvisit_visitfishsize_check;
ALTER TABLE vpvisit
    ADD CONSTRAINT vpvisit_visitfishsize_check
    CHECK ("visitFishSize" IS NULL OR "visitFishSize" IN ('Small', 'Medium', 'Large'));

COMMENT ON COLUMN vpvisit."visitFishSize" IS
  'Size class of fish observed: Small, Medium or Large. NULL where not recorded.';

-- ── The views are NOT recreated here ────────────────────────────────────────
-- They are dropped above because ALTER COLUMN TYPE cannot run while a view
-- depends on the column, and migration 025 is their sole definition.
--
-- An earlier revision of this file embedded a copy of the CREATE VIEW
-- statements. That was a trap: 025 later changed how dates are published, so any
-- re-run of 023 silently reverted the views to the older definition while 025,
-- already recorded as applied, never ran again to put them back. Migrations that
-- each carry their own copy of a generated artefact cannot be replayed safely.
--
-- Filename order guarantees 025 follows this file, so a fresh database gets the
-- views from 025 and an existing one keeps whatever 025 last built.

-- Grants live with the view definitions in 025, since the views do not exist
-- at this point in the sequence.
