-- =============================================================================
-- 028_correct_numeric_widths_in_comments.sql
-- =============================================================================
-- Rebuilds both publication views so the numeric constraints in the column
-- comments are stated in decimal digits rather than bits.
--
-- WHY
--   The dictionary took its numeric width from information_schema's
--   numeric_precision, which is only a digit count when numeric_precision_radix
--   is 10 -- true for `numeric` alone. For the binary types the radix is 2 and
--   the value is a BIT width: an `integer` reports 32 and a `real` reports 24.
--
--   So visitMaxWidth, which holds at most 10 digits, was published as 32, and
--   every `real` column claimed 24 digits with no decimal places. Wrong in the
--   x-dbfWidth extension, wrong in the constraint text of each comment, and it
--   would have sized a DBF field three times wider than needed.
--
--   _schema/build_dictionary.js now maps each binary type to the decimal digits
--   it can actually hold, and falls back to numeric_precision only when the
--   radix says that value is decimal.
--
-- Column lists are generated by _schema/build_views.js; regenerate rather than
-- editing them here.
--
-- NOTE FOR OPERATORS
--   pg_featureserv caches collection metadata at startup. Restart ogc_vp after
--   this migration or the OGC collection keeps serving the previous comments.
-- =============================================================================

-- ── Collection: mapped_pools (20 published fields + geom) ────────────────────
DROP VIEW IF EXISTS ogc.mapped_pools CASCADE;
CREATE VIEW ogc.mapped_pools AS
SELECT
    m."mappedPoolId"                                              AS "poolId",
    (m."mappedPoolStatus")::text                                  AS "poolStatus",
    t."townName"                                                  AS "townName",
    c."countyName"                                                AS "countyName",
    CONCAT('https://vpatlas.org/pools/list?poolId=', m."mappedPoolId", '&zoomFilter=false') AS "vpatlas_pool_url",
    m."mappedPoolId"                                              AS "mappedPoolId",
    to_char(m."mappedDateText", 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')  AS "mappedDateText",
    m."mappedLatitude"                                            AS "mappedLatitude",
    m."mappedLongitude"                                           AS "mappedLongitude",
    (m."mappedConfidence")::text                                  AS "mappedConfidence",
    m."mappedSource"                                              AS "mappedSource",
    m."mappedSource2"                                             AS "mappedSource2",
    m."mappedPhotoNumber"                                         AS "mappedPhotoNumber",
    (m."mappedLocationAccuracy")::text                            AS "mappedLocationAccuracy",
    to_char(m."createdAt", 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')       AS "createdAt",
    to_char(m."updatedAt", 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')       AS "updatedAt",
    (m."mappedMethod")::text                                      AS "mappedMethod",
    (m."mappedLandownerPermission")::int::smallint                AS "mappedLandownerPermission",
    m."mappedLocationUncertainty"                                 AS "mappedLocationUncertainty",
    (m."mappedPoolStatus")::text                                  AS "mappedPoolStatus",
    m."mappedPoolLocation"                                        AS geom
FROM vpmapped m
LEFT JOIN vptown   t ON m."mappedTownId"  = t."townId"
LEFT JOIN vpcounty c ON t."townCountyId"  = c."govCountyId"
WHERE m."mappedPoolLocation" IS NOT NULL
  AND (m."mappedPoolStatus" IS NULL
       OR m."mappedPoolStatus" NOT IN ('Eliminated', 'Duplicate'));

COMMENT ON VIEW ogc.mapped_pools IS
  'Canonical publication view for mapped vernal pools. Generated from _schema/mapped.json; do not hand-edit. Feeds /mapped/geojson, /mapped/shapefile and the OGC API - Features collection identically. Excludes landowner PII, contributor identity and internal system identifiers.';

-- Field descriptions, published by pg_featureserv as each field's description.
COMMENT ON COLUMN ogc.mapped_pools."poolId" IS
  'Alias of mappedPoolId, retained for compatibility. [max 20 characters]';
COMMENT ON COLUMN ogc.mapped_pools."poolStatus" IS
  'Alias of mappedPoolStatus, retained for compatibility. [max 10 characters; allowed values: Potential, Probable, Confirmed, Eliminated, Duplicate]';
COMMENT ON COLUMN ogc.mapped_pools."townName" IS
  'Town containing the pool. [max 20 characters]';
COMMENT ON COLUMN ogc.mapped_pools."countyName" IS
  'County containing the pool. Stored uppercase. [max 10 characters]';
COMMENT ON COLUMN ogc.mapped_pools."vpatlas_pool_url" IS
  'Deep link to the pool on vpatlas.org. [max 75 characters]';
COMMENT ON COLUMN ogc.mapped_pools."mappedPoolId" IS
  'Unique VPAtlas identifier for the pool. Identifiers prefixed NEW were assigned by the atlas; others carry the identifier from the source dataset. [max 20 characters]';
COMMENT ON COLUMN ogc.mapped_pools."mappedDateText" IS
  'Date the pool was mapped or first entered into the atlas. [ISO-8601 UTC (YYYY-MM-DDTHH:MM:SS.mmmZ)]';
COMMENT ON COLUMN ogc.mapped_pools."mappedLatitude" IS
  'Latitude of the mapped pool centre, WGS84 decimal degrees. [decimal, 11 digits with 8 decimal places]';
COMMENT ON COLUMN ogc.mapped_pools."mappedLongitude" IS
  'Longitude of the mapped pool centre, WGS84 decimal degrees. [decimal, 11 digits with 8 decimal places]';
COMMENT ON COLUMN ogc.mapped_pools."mappedConfidence" IS
  'Mapper''s confidence that the mapped feature is a vernal pool, from L (low) through H (high). UNK where not assessed. [max 10 characters; allowed values: L, ML, M, MH, H, UNK]';
COMMENT ON COLUMN ogc.mapped_pools."mappedSource" IS
  'Dataset, project or organisation the pool record originated from. [max 50 characters]';
COMMENT ON COLUMN ogc.mapped_pools."mappedSource2" IS
  'Secondary source, where the record was corroborated by or merged from more than one origin. [max 10 characters]';
COMMENT ON COLUMN ogc.mapped_pools."mappedPhotoNumber" IS
  'Reference number of the photograph taken of the pool, where one exists. [max 10 characters]';
COMMENT ON COLUMN ogc.mapped_pools."mappedLocationAccuracy" IS
  'Confidence in the positional accuracy of the mapped coordinates, from L (low) through H (high). UNK where not assessed. [max 10 characters; allowed values: L, ML, M, MH, H, UNK]';
COMMENT ON COLUMN ogc.mapped_pools."createdAt" IS
  'Timestamp the record was created in VPAtlas (UTC). [ISO-8601 UTC (YYYY-MM-DDTHH:MM:SS.mmmZ)]';
COMMENT ON COLUMN ogc.mapped_pools."updatedAt" IS
  'Timestamp the record was last modified in VPAtlas (UTC). [ISO-8601 UTC (YYYY-MM-DDTHH:MM:SS.mmmZ)]';
COMMENT ON COLUMN ogc.mapped_pools."mappedMethod" IS
  'How the pool was identified: Aerial photography, CIR or LiDAR imagery, NDWI, a field Visit or Survey, or previously Known. [max 10 characters; allowed values: Aerial, Known, Visit, Survey, CIR, LiDAR, LiDAR_NDWI, NDWI]';
COMMENT ON COLUMN ogc.mapped_pools."mappedLandownerPermission" IS
  'Whether landowner permission to access the pool is on record. 1 = yes, 0 = no. Landowner identity is not published. [0 or 1]';
COMMENT ON COLUMN ogc.mapped_pools."mappedLocationUncertainty" IS
  'Positional uncertainty of the mapped coordinates as recorded by the mapper. [max 20 characters]';
COMMENT ON COLUMN ogc.mapped_pools."mappedPoolStatus" IS
  'Verification status of the pool. Potential means mapped but unvisited; Probable and Confirmed reflect field evidence. Eliminated and Duplicate records are not published. [max 10 characters; allowed values: Potential, Probable, Confirmed, Eliminated, Duplicate]';

-- ── Collection: pool_visits (108 published fields + geom) ────────────────────
DROP VIEW IF EXISTS ogc.pool_visits CASCADE;
CREATE VIEW ogc.pool_visits AS
SELECT
    m."mappedPoolId"                                              AS "poolId",
    (m."mappedPoolStatus")::text                                  AS "poolStatus",
    t."townName"                                                  AS "townName",
    c."countyName"                                                AS "countyName",
    CONCAT('https://vpatlas.org/pools/list?poolId=', m."mappedPoolId", '&zoomFilter=false') AS "vpatlas_pool_url",
    CONCAT('https://vpatlas.org/pools/visit/view/', v."visitId")  AS "vpatlas_visit_url",
    v."visitId"                                                   AS "visitId",
    v."visitPoolId"                                               AS "visitPoolId",
    to_char(v."visitDate", 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')       AS "visitDate",
    (v."visitLocatePool")::int::smallint                          AS "visitLocatePool",
    CASE WHEN v."visitCertainty" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitCertainty", '[\[\]"]', '', 'g')) ELSE v."visitCertainty" END AS "visitCertainty",
    CASE WHEN v."visitNavMethod" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitNavMethod", '[\[\]"]', '', 'g')) ELSE v."visitNavMethod" END AS "visitNavMethod",
    v."visitCoordSource"                                          AS "visitCoordSource",
    v."visitLatitude"                                             AS "visitLatitude",
    v."visitLongitude"                                            AS "visitLongitude",
    CASE WHEN v."visitVernalPool" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitVernalPool", '[\[\]"]', '', 'g')) ELSE v."visitVernalPool" END AS "visitVernalPool",
    CASE WHEN v."visitPoolType" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitPoolType", '[\[\]"]', '', 'g')) ELSE v."visitPoolType" END AS "visitPoolType",
    CASE WHEN v."visitInletType" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitInletType", '[\[\]"]', '', 'g')) ELSE v."visitInletType" END AS "visitInletType",
    CASE WHEN v."visitOutletType" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitOutletType", '[\[\]"]', '', 'g')) ELSE v."visitOutletType" END AS "visitOutletType",
    CASE WHEN v."visitForestUpland" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitForestUpland", '[\[\]"]', '', 'g')) ELSE v."visitForestUpland" END AS "visitForestUpland",
    CASE WHEN v."visitForestCondition" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitForestCondition", '[\[\]"]', '', 'g')) ELSE v."visitForestCondition" END AS "visitForestCondition",
    (v."visitHabitatAgriculture")::int::smallint                  AS "visitHabitatAgriculture",
    (v."visitHabitatLightDev")::int::smallint                     AS "visitHabitatLightDev",
    (v."visitHabitatHeavyDev")::int::smallint                     AS "visitHabitatHeavyDev",
    (v."visitHabitatPavedRd")::int::smallint                      AS "visitHabitatPavedRd",
    (v."visitHabitatDirtRd")::int::smallint                       AS "visitHabitatDirtRd",
    (v."visitHabitatPowerline")::int::smallint                    AS "visitHabitatPowerline",
    v."visitHabitatOther"                                         AS "visitHabitatOther",
    v."visitHabitatComment"                                       AS "visitHabitatComment",
    v."visitMaxDepth"                                             AS "visitMaxDepth",
    CASE WHEN v."visitWaterLevelObs" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitWaterLevelObs", '[\[\]"]', '', 'g')) ELSE v."visitWaterLevelObs" END AS "visitWaterLevelObs",
    CASE WHEN v."visitHydroPeriod" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitHydroPeriod", '[\[\]"]', '', 'g')) ELSE v."visitHydroPeriod" END AS "visitHydroPeriod",
    v."visitMaxWidth"                                             AS "visitMaxWidth",
    v."visitMaxLength"                                            AS "visitMaxLength",
    v."visitPoolTrees"                                            AS "visitPoolTrees",
    v."visitPoolShrubs"                                           AS "visitPoolShrubs",
    v."visitPoolEmergents"                                        AS "visitPoolEmergents",
    v."visitPoolFloatingVeg"                                      AS "visitPoolFloatingVeg",
    CASE WHEN v."visitSubstrate" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitSubstrate", '[\[\]"]', '', 'g')) ELSE v."visitSubstrate" END AS "visitSubstrate",
    (v."visitDisturbDumping")::int::smallint                      AS "visitDisturbDumping",
    (v."visitDisturbSiltation")::int::smallint                    AS "visitDisturbSiltation",
    (v."visitDisturbVehicleRuts")::int::smallint                  AS "visitDisturbVehicleRuts",
    (v."visitDisturbRunoff")::int::smallint                       AS "visitDisturbRunoff",
    (v."visitDisturbDitching")::int::smallint                     AS "visitDisturbDitching",
    v."visitDisturbOther"                                         AS "visitDisturbOther",
    v."visitWoodFrogAdults"                                       AS "visitWoodFrogAdults",
    v."visitWoodFrogLarvae"                                       AS "visitWoodFrogLarvae",
    v."visitWoodFrogEgg"                                          AS "visitWoodFrogEgg",
    CASE WHEN v."visitWoodFrogEggHow" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitWoodFrogEggHow", '[\[\]"]', '', 'g')) ELSE v."visitWoodFrogEggHow" END AS "visitWoodFrogEggHow",
    v."visitSpsAdults"                                            AS "visitSpsAdults",
    v."visitSpsLarvae"                                            AS "visitSpsLarvae",
    v."visitSpsEgg"                                               AS "visitSpsEgg",
    CASE WHEN v."visitSpsEggHow" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitSpsEggHow", '[\[\]"]', '', 'g')) ELSE v."visitSpsEggHow" END AS "visitSpsEggHow",
    v."visitJesaAdults"                                           AS "visitJesaAdults",
    v."visitJesaLarvae"                                           AS "visitJesaLarvae",
    v."visitJesaEgg"                                              AS "visitJesaEgg",
    CASE WHEN v."visitJesaEggHow" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitJesaEggHow", '[\[\]"]', '', 'g')) ELSE v."visitJesaEggHow" END AS "visitJesaEggHow",
    v."visitBssaAdults"                                           AS "visitBssaAdults",
    v."visitBssaLarvae"                                           AS "visitBssaLarvae",
    v."visitBssaEgg"                                              AS "visitBssaEgg",
    CASE WHEN v."visitBssaEggHow" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitBssaEggHow", '[\[\]"]', '', 'g')) ELSE v."visitBssaEggHow" END AS "visitBssaEggHow",
    v."visitFairyShrimp"                                          AS "visitFairyShrimp",
    v."visitFingerNailClams"                                      AS "visitFingerNailClams",
    v."visitSpeciesOther1"                                        AS "visitSpeciesOther1",
    v."visitSpeciesOther2"                                        AS "visitSpeciesOther2",
    (v."visitFish")::int::smallint                                AS "visitFish",
    v."visitFishCount"                                            AS "visitFishCount",
    v."visitFishSizeSmall"                                        AS "visitFishSizeSmall",
    v."visitFishSizeMedium"                                       AS "visitFishSizeMedium",
    v."visitFishSizeLarge"                                        AS "visitFishSizeLarge",
    to_char(v."createdAt", 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')       AS "createdAt",
    to_char(v."updatedAt", 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')       AS "updatedAt",
    (v."visitPoolMapped")::int::smallint                          AS "visitPoolMapped",
    (v."visitUserIsLandowner")::int::smallint                     AS "visitUserIsLandowner",
    (v."visitLandownerPermission")::int::smallint                 AS "visitLandownerPermission",
    CASE WHEN v."visitFishSize" ~ '^\s*\[' THEN btrim(regexp_replace(v."visitFishSize", '[\[\]"]', '', 'g')) ELSE v."visitFishSize" END AS "visitFishSize",
    v."visitNavMethodOther"                                       AS "visitNavMethodOther",
    v."visitPoolTypeOther"                                        AS "visitPoolTypeOther",
    v."visitSubstrateOther"                                       AS "visitSubstrateOther",
    v."visitSpeciesOtherName"                                     AS "visitSpeciesOtherName",
    v."visitSpeciesOtherCount"                                    AS "visitSpeciesOtherCount",
    v."visitLocationUncertainty"                                  AS "visitLocationUncertainty",
    v."visitSubmergedVeg"                                         AS "visitSubmergedVeg",
    (v."visitHabitatTrails")::int::smallint                       AS "visitHabitatTrails",
    (v."visitAmphibianDisease")::int::smallint                    AS "visitAmphibianDisease",
    to_char(v."lastEditedAt", 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')    AS "lastEditedAt",
    m."mappedPoolId"                                              AS "mappedPoolId",
    to_char(m."mappedDateText", 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')  AS "mappedDateText",
    m."mappedLatitude"                                            AS "mappedLatitude",
    m."mappedLongitude"                                           AS "mappedLongitude",
    (m."mappedConfidence")::text                                  AS "mappedConfidence",
    m."mappedSource"                                              AS "mappedSource",
    m."mappedSource2"                                             AS "mappedSource2",
    m."mappedPhotoNumber"                                         AS "mappedPhotoNumber",
    (m."mappedLocationAccuracy")::text                            AS "mappedLocationAccuracy",
    (m."mappedMethod")::text                                      AS "mappedMethod",
    (m."mappedLandownerPermission")::int::smallint                AS "mappedLandownerPermission",
    m."mappedLocationUncertainty"                                 AS "mappedLocationUncertainty",
    (m."mappedPoolStatus")::text                                  AS "mappedPoolStatus",
    r."reviewId"                                                  AS "reviewId",
    r."reviewPoolId"                                              AS "reviewPoolId",
    r."reviewVisitId"                                             AS "reviewVisitId",
    r."reviewQACode"                                              AS "reviewQACode",
    r."reviewQAAlt"                                               AS "reviewQAAlt",
    to_char(r."reviewQADate", 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')    AS "reviewQADate",
    (r."reviewPoolStatus")::text                                  AS "reviewPoolStatus",
    (r."reviewPoolLocator")::int::smallint                        AS "reviewPoolLocator",
    NULLIF(array_to_string(COALESCE(r."reviewReasons", '{}'::text[]), ', '), '') AS "reviewReasons",
    m."mappedPoolLocation"                                        AS geom
FROM vpvisit v
INNER JOIN vpmapped m ON v."visitPoolId"   = m."mappedPoolId"
LEFT  JOIN vptown   t ON m."mappedTownId"  = t."townId"
LEFT  JOIN vpcounty c ON t."townCountyId"  = c."govCountyId"
LEFT  JOIN vpreview r ON v."visitId"       = r."reviewVisitId"
WHERE m."mappedPoolLocation" IS NOT NULL
  AND (m."mappedPoolStatus" IS NULL
       OR m."mappedPoolStatus" NOT IN ('Eliminated', 'Duplicate'));

COMMENT ON VIEW ogc.pool_visits IS
  'Canonical publication view for pool visits. Generated from _schema/visit.json; do not hand-edit. Feeds /visit/geojson, /visit/shapefile and the OGC API - Features collection identically. Excludes landowner PII, contributor identity and internal system identifiers.';

-- Field descriptions, published by pg_featureserv as each field's description.
COMMENT ON COLUMN ogc.pool_visits."poolId" IS
  'Alias of mappedPoolId, retained for compatibility. [max 20 characters]';
COMMENT ON COLUMN ogc.pool_visits."poolStatus" IS
  'Alias of mappedPoolStatus, retained for compatibility. [max 10 characters; allowed values: Potential, Probable, Confirmed, Eliminated, Duplicate]';
COMMENT ON COLUMN ogc.pool_visits."townName" IS
  'Town containing the pool. [max 20 characters]';
COMMENT ON COLUMN ogc.pool_visits."countyName" IS
  'County containing the pool. Stored uppercase. [max 10 characters]';
COMMENT ON COLUMN ogc.pool_visits."vpatlas_pool_url" IS
  'Deep link to the pool on vpatlas.org. [max 75 characters]';
COMMENT ON COLUMN ogc.pool_visits."vpatlas_visit_url" IS
  'Deep link to the visit on vpatlas.org. [max 50 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitId" IS
  'Unique identifier for this visit record. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitPoolId" IS
  'Identifier of the pool visited; joins to mappedPoolId. [max 10 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitDate" IS
  'Date the pool was visited. [ISO-8601 UTC (YYYY-MM-DDTHH:MM:SS.mmmZ)]';
COMMENT ON COLUMN ogc.pool_visits."visitLocatePool" IS
  'Whether the observer located the pool in the field. 1 = yes, 0 = no; null means not recorded. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitCertainty" IS
  'Observer''s certainty that the feature found was the mapped pool: Certain, Pretty Sure or Not Sure. [max 20 characters; allowed values: Certain, Pretty Sure, Not Sure]';
COMMENT ON COLUMN ogc.pool_visits."visitNavMethod" IS
  'How the observer navigated to the pool: GPS, Map, Map and compass, prior knowledge of the site, or other. [max 20 characters; allowed values: GPS, Map, Map & Compass, Prior Knowledge, Other]';
COMMENT ON COLUMN ogc.pool_visits."visitCoordSource" IS
  'Source of the coordinates used to find the pool, often the name of an originating shapefile or GPS. [max 50 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitLatitude" IS
  'Latitude recorded at the pool during the visit, WGS84 decimal degrees. [decimal, 11 digits with 8 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."visitLongitude" IS
  'Longitude recorded at the pool during the visit, WGS84 decimal degrees. [decimal, 11 digits with 8 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."visitVernalPool" IS
  'Observer''s determination of whether the feature is a vernal pool: Yes, No or Don''t Know. [max 10 characters; allowed values: Yes, No, Don''t Know]';
COMMENT ON COLUMN ogc.pool_visits."visitPoolType" IS
  'Landform setting of the pool, such as Isolated Forest Depression, Floodplain Depression, or Manmade. [max 50 characters; allowed values: Isolated Forest Depression, Isolated Non-Forest Depression, Floodplain Depression, Pool associated with larger wetland complex, Manmade, Other]';
COMMENT ON COLUMN ogc.pool_visits."visitInletType" IS
  'Nature of any inflow to the pool: No Inlet, Ephemeral Inlet or Permanent Inlet. [max 20 characters; allowed values: No Inlet, Ephemeral Inlet, Permanent Inlet]';
COMMENT ON COLUMN ogc.pool_visits."visitOutletType" IS
  'Nature of any outflow from the pool: No Outlet, Ephemeral Outlet or Permanent Outlet. [max 20 characters; allowed values: No Outlet, Ephemeral Outlet, Permanent Outlet]';
COMMENT ON COLUMN ogc.pool_visits."visitForestUpland" IS
  'Dominant forest type of the surrounding upland. Hardwood and Deciduous are equivalent, as are Softwood and Coniferous; both spellings persist in the data and each activates the same form control. [max 10 characters; allowed values: Hardwood, Deciduous, Softwood, Coniferous, Mixed, Open/Field, Other]';
COMMENT ON COLUMN ogc.pool_visits."visitForestCondition" IS
  'Condition of the surrounding forest. Minor logging and Major logging are both represented by the form''s single Recently Logged option; the stored distinction is preserved on edit. [max 20 characters; allowed values: Undisturbed, Recently Logged, Minor logging, Major logging, Old Growth, Other]';
COMMENT ON COLUMN ogc.pool_visits."visitHabitatAgriculture" IS
  'Agricultural land present in the surrounding habitat. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitHabitatLightDev" IS
  'Light development present in the surrounding habitat. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitHabitatHeavyDev" IS
  'Heavy development present in the surrounding habitat. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitHabitatPavedRd" IS
  'Paved road present in the surrounding habitat. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitHabitatDirtRd" IS
  'Dirt road present in the surrounding habitat. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitHabitatPowerline" IS
  'Powerline corridor present in the surrounding habitat. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitHabitatOther" IS
  'Other surrounding habitat feature not covered by the habitat flags. [max 150 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitHabitatComment" IS
  'Observer''s notes on the surrounding habitat. Truncated to 254 characters in the shapefile export. [max 254 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitMaxDepth" IS
  'Maximum water depth observed. Free text; values range from measurements to descriptive depths such as ''Knee-deep''. [max 20 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitWaterLevelObs" IS
  'Water level at the time of the visit: Full, More than 50%, Less than 50%, or Dry. [max 20 characters; allowed values: Full, More than 50%, Less than 50%, Dry]';
COMMENT ON COLUMN ogc.pool_visits."visitHydroPeriod" IS
  'How long the pool holds water: Ephemeral, Dries annually, Dries every 5 years, Semi-permanent, Never dries or Permanent. [max 20 characters; allowed values: Ephemeral, Dries annually, Dries every 5 years, Semi-permanent, Never dries, Permanent]';
COMMENT ON COLUMN ogc.pool_visits."visitMaxWidth" IS
  'Maximum width of the pool, in feet. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitMaxLength" IS
  'Maximum length of the pool, in feet. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitPoolTrees" IS
  'Percent of the pool shaded or occupied by trees, 0-100. [decimal, 14 digits with 6 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."visitPoolShrubs" IS
  'Percent of the pool occupied by shrubs, 0-100. [decimal, 14 digits with 6 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."visitPoolEmergents" IS
  'Percent of the pool occupied by emergent vegetation, 0-100. [decimal, 14 digits with 6 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."visitPoolFloatingVeg" IS
  'Percent of the pool occupied by floating vegetation, 0-100. [decimal, 14 digits with 6 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."visitSubstrate" IS
  'Dominant pool substrate: Leaf litter, Mud, Sand/Gravel, Bedrock or Other. [max 20 characters; allowed values: Leaf litter, Mud, Sand/Gravel, Bedrock, Other]';
COMMENT ON COLUMN ogc.pool_visits."visitDisturbDumping" IS
  'Evidence of dumping at the pool. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitDisturbSiltation" IS
  'Evidence of siltation at the pool. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitDisturbVehicleRuts" IS
  'Evidence of vehicle ruts at the pool. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitDisturbRunoff" IS
  'Evidence of runoff affecting the pool. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitDisturbDitching" IS
  'Evidence of ditching at or near the pool. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitDisturbOther" IS
  'Other disturbance observed, not covered by the disturbance flags. [max 150 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitWoodFrogAdults" IS
  'Count of adult wood frogs (Lithobates sylvaticus) observed. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitWoodFrogLarvae" IS
  'Count of wood frog larvae observed. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitWoodFrogEgg" IS
  'Count of wood frog egg masses observed. A primary vernal pool indicator. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitWoodFrogEggHow" IS
  'Whether the wood frog egg mass count was Counted or Estimated. [max 10 characters; allowed values: Counted, Estimated]';
COMMENT ON COLUMN ogc.pool_visits."visitSpsAdults" IS
  'Count of adult spotted salamanders (Ambystoma maculatum) observed. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitSpsLarvae" IS
  'Count of spotted salamander larvae observed. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitSpsEgg" IS
  'Count of spotted salamander egg masses observed. A primary vernal pool indicator. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitSpsEggHow" IS
  'Whether the spotted salamander egg mass count was Counted or Estimated. [max 10 characters; allowed values: Counted, Estimated]';
COMMENT ON COLUMN ogc.pool_visits."visitJesaAdults" IS
  'Count of adult Jefferson salamanders (Ambystoma jeffersonianum) observed. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitJesaLarvae" IS
  'Count of Jefferson salamander larvae observed. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitJesaEgg" IS
  'Count of Jefferson salamander egg masses observed. A primary vernal pool indicator. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitJesaEggHow" IS
  'Whether the Jefferson salamander egg mass count was Counted or Estimated. [max 10 characters; allowed values: Counted, Estimated]';
COMMENT ON COLUMN ogc.pool_visits."visitBssaAdults" IS
  'Count of adult blue-spotted salamanders (Ambystoma laterale) observed. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitBssaLarvae" IS
  'Count of blue-spotted salamander larvae observed. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitBssaEgg" IS
  'Count of blue-spotted salamander egg masses observed. A primary vernal pool indicator. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitBssaEggHow" IS
  'Whether the blue-spotted salamander egg mass count was Counted or Estimated. [max 10 characters; allowed values: Counted, Estimated]';
COMMENT ON COLUMN ogc.pool_visits."visitFairyShrimp" IS
  'Count of fairy shrimp (Anostraca) observed. A primary vernal pool indicator. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitFingerNailClams" IS
  'Count of fingernail clams (Sphaeriidae) observed. A secondary vernal pool indicator. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitSpeciesOther1" IS
  'Additional species observed at the pool. [max 50 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitSpeciesOther2" IS
  'Further additional species observed at the pool. [max 100 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitFish" IS
  'Fish observed in the pool. 1 = yes, 0 = no. Fish presence generally disqualifies a pool as vernal habitat. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitFishCount" IS
  'Number of fish observed. Free text; may hold a count or a descriptive abundance. [max 10 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitFishSizeSmall" IS
  'Fish abundance recorded for the small size class. Sparsely recorded. [decimal, 14 digits with 6 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."visitFishSizeMedium" IS
  'Fish abundance recorded for the medium size class. Sparsely recorded. [decimal, 14 digits with 6 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."visitFishSizeLarge" IS
  'Fish abundance recorded for the large size class. Sparsely recorded. [decimal, 14 digits with 6 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."createdAt" IS
  'Timestamp the visit record was created in VPAtlas (UTC). [ISO-8601 UTC (YYYY-MM-DDTHH:MM:SS.mmmZ)]';
COMMENT ON COLUMN ogc.pool_visits."updatedAt" IS
  'Timestamp the visit record was last modified in VPAtlas (UTC). [ISO-8601 UTC (YYYY-MM-DDTHH:MM:SS.mmmZ)]';
COMMENT ON COLUMN ogc.pool_visits."visitPoolMapped" IS
  'Whether the pool had already been mapped before this visit. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitUserIsLandowner" IS
  'Whether the observer was the landowner. 1 = yes, 0 = no. Observer identity is not published. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitLandownerPermission" IS
  'Whether landowner permission for this visit is on record. 1 = yes, 0 = no. Landowner identity is not published. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitFishSize" IS
  'Size class of fish observed: Small, Medium or Large. [max 10 characters; allowed values: Small, Medium, Large]';
COMMENT ON COLUMN ogc.pool_visits."visitNavMethodOther" IS
  'Navigation method, where visitNavMethod is Other. [max 150 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitPoolTypeOther" IS
  'Pool type, where visitPoolType is Other. [max 150 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitSubstrateOther" IS
  'Substrate, where visitSubstrate is Other. [max 75 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitSpeciesOtherName" IS
  'Name of the additional species recorded in visitSpeciesOtherCount. [max 50 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitSpeciesOtherCount" IS
  'Count of the additional species named in visitSpeciesOtherName. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."visitLocationUncertainty" IS
  'Positional uncertainty of the visit coordinates as recorded by the observer. [max 10 characters]';
COMMENT ON COLUMN ogc.pool_visits."visitSubmergedVeg" IS
  'Percent of the pool occupied by submerged vegetation, 0-100. [decimal, 14 digits with 6 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."visitHabitatTrails" IS
  'Trails present in the surrounding habitat. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."visitAmphibianDisease" IS
  'Signs of amphibian disease observed. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."lastEditedAt" IS
  'Timestamp the visit record was last edited (UTC). [ISO-8601 UTC (YYYY-MM-DDTHH:MM:SS.mmmZ)]';
COMMENT ON COLUMN ogc.pool_visits."mappedPoolId" IS
  'Unique VPAtlas identifier for the pool. Identifiers prefixed NEW were assigned by the atlas; others carry the identifier from the source dataset. [max 20 characters]';
COMMENT ON COLUMN ogc.pool_visits."mappedDateText" IS
  'Date the pool was mapped or first entered into the atlas. [ISO-8601 UTC (YYYY-MM-DDTHH:MM:SS.mmmZ)]';
COMMENT ON COLUMN ogc.pool_visits."mappedLatitude" IS
  'Latitude of the mapped pool centre, WGS84 decimal degrees. [decimal, 11 digits with 8 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."mappedLongitude" IS
  'Longitude of the mapped pool centre, WGS84 decimal degrees. [decimal, 11 digits with 8 decimal places]';
COMMENT ON COLUMN ogc.pool_visits."mappedConfidence" IS
  'Mapper''s confidence that the mapped feature is a vernal pool, from L (low) through H (high). UNK where not assessed. [max 10 characters; allowed values: L, ML, M, MH, H, UNK]';
COMMENT ON COLUMN ogc.pool_visits."mappedSource" IS
  'Dataset, project or organisation the pool record originated from. [max 50 characters]';
COMMENT ON COLUMN ogc.pool_visits."mappedSource2" IS
  'Secondary source, where the record was corroborated by or merged from more than one origin. [max 10 characters]';
COMMENT ON COLUMN ogc.pool_visits."mappedPhotoNumber" IS
  'Reference number of the photograph taken of the pool, where one exists. [max 10 characters]';
COMMENT ON COLUMN ogc.pool_visits."mappedLocationAccuracy" IS
  'Confidence in the positional accuracy of the mapped coordinates, from L (low) through H (high). UNK where not assessed. [max 10 characters; allowed values: L, ML, M, MH, H, UNK]';
COMMENT ON COLUMN ogc.pool_visits."mappedMethod" IS
  'How the pool was identified: Aerial photography, CIR or LiDAR imagery, NDWI, a field Visit or Survey, or previously Known. [max 10 characters; allowed values: Aerial, Known, Visit, Survey, CIR, LiDAR, LiDAR_NDWI, NDWI]';
COMMENT ON COLUMN ogc.pool_visits."mappedLandownerPermission" IS
  'Whether landowner permission to access the pool is on record. 1 = yes, 0 = no. Landowner identity is not published. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."mappedLocationUncertainty" IS
  'Positional uncertainty of the mapped coordinates as recorded by the mapper. [max 20 characters]';
COMMENT ON COLUMN ogc.pool_visits."mappedPoolStatus" IS
  'Verification status of the pool. Potential means mapped but unvisited; Probable and Confirmed reflect field evidence. Eliminated and Duplicate records are not published. [max 10 characters; allowed values: Potential, Probable, Confirmed, Eliminated, Duplicate]';
COMMENT ON COLUMN ogc.pool_visits."reviewId" IS
  'Unique identifier for the quality-assurance review of this visit, where one exists. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."reviewPoolId" IS
  'Identifier of the pool the review applies to. [max 10 characters]';
COMMENT ON COLUMN ogc.pool_visits."reviewVisitId" IS
  'Identifier of the visit the review applies to. [whole number]';
COMMENT ON COLUMN ogc.pool_visits."reviewQACode" IS
  'Quality-assurance outcome code assigned by the reviewer. [max 20 characters]';
COMMENT ON COLUMN ogc.pool_visits."reviewQAAlt" IS
  'Alternate quality-assurance code, where the reviewer recorded one. [max 100 characters]';
COMMENT ON COLUMN ogc.pool_visits."reviewQADate" IS
  'Date the quality-assurance review was completed. [ISO-8601 UTC (YYYY-MM-DDTHH:MM:SS.mmmZ)]';
COMMENT ON COLUMN ogc.pool_visits."reviewPoolStatus" IS
  'Pool status assigned by the reviewer, which may differ from the status recorded at the visit. [max 10 characters; allowed values: Potential, Probable, Confirmed, Eliminated, Duplicate]';
COMMENT ON COLUMN ogc.pool_visits."reviewPoolLocator" IS
  'Whether the reviewer could locate the pool from the visit record. 1 = yes, 0 = no. [0 or 1]';
COMMENT ON COLUMN ogc.pool_visits."reviewReasons" IS
  'Reasons recorded by the reviewer for the assigned status, as a comma-delimited list. [max 100 characters]';

GRANT USAGE  ON SCHEMA ogc       TO pgfs_reader;
GRANT SELECT ON ogc.mapped_pools TO pgfs_reader;
GRANT SELECT ON ogc.pool_visits  TO pgfs_reader;
