#!/bin/bash
# entrypoint.sh - Generate config.js from environment variables
#
# Usage:
#   Docker:     ./entrypoint.sh node server.js     (uses env vars, writes to /opt/ui/...)
#   Local dev:  ./entrypoint.sh --local            (loads .env, writes to ./uiVPAtlas/...)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LOCAL_MODE=false
ENV_FILE=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --local)
            LOCAL_MODE=true
            shift
            ;;
        --env)
            ENV_FILE="$2"
            shift 2
            ;;
        *)
            break  # Remaining args are the command to exec
            ;;
    esac
done

# Set base path based on mode
if [ "$LOCAL_MODE" = true ]; then
    BASE_PATH="$SCRIPT_DIR/uiVPAtlas"

    # Auto-load .env if no --env specified and .env exists
    if [ -z "$ENV_FILE" ] && [ -f "$SCRIPT_DIR/.env" ]; then
        ENV_FILE="$SCRIPT_DIR/.env"
    fi

    # Load env file if found
    if [ -n "$ENV_FILE" ] && [ -f "$ENV_FILE" ]; then
        echo "Loading environment from: $ENV_FILE"
        set -a
        source "$ENV_FILE"
        set +a
    else
        echo "No .env file found - using current environment or defaults"
    fi
else
    BASE_PATH="/opt/ui/uiVPAtlas"
fi

echo "=============================================="
echo "Generating VPAtlas UI config.js"
echo "Mode: $([ "$LOCAL_MODE" = true ] && echo 'LOCAL DEV' || echo 'DOCKER')"
echo "Base path: $BASE_PATH"
echo "=============================================="

# Defaults
API_PROT="${API_PROT:-http}"
API_HOST="${API_HOST:-localhost}"
API_PORT="${API_PORT:-4010}"
UI_PROT="${UI_PROT:-http}"
UI_HOST="${UI_HOST:-localhost}"
UI_PORT="${UI_PORT:-8090}"

# Build FQDNs (only include port for localhost)
if [ "$API_HOST" = "localhost" ]; then
    API_FQDN="${API_PROT}://${API_HOST}:${API_PORT}"
else
    API_FQDN="${API_PROT}://${API_HOST}"
fi

if [ "$UI_HOST" = "localhost" ]; then
    UI_FQDN="${UI_PROT}://${UI_HOST}:${UI_PORT}"
else
    UI_FQDN="${UI_PROT}://${UI_HOST}"
fi

echo "API: $API_FQDN"
echo "UI:  $UI_FQDN"
echo "=============================================="

# =============================================================================
# SHARED CONFIG (classic script with global appConfig)
# =============================================================================
CONFIG_CONTENT="// Auto-generated by entrypoint.sh - do not edit manually
// Shared config for /explore and /survey apps
// Load via <script src=\"/js/config.js\"></script> BEFORE other scripts
const appConfig = {ui:{}, api:{}};

// Set the UI config by reading the location
appConfig.ui.protocol = location.protocol.split(':')[0];
appConfig.ui.host = location.host;
appConfig.ui.name = location.host.split(':')[0];
appConfig.ui.port = location.host.split(':')[1] ? location.host.split(':')[1] : '';
appConfig.ui.path = location.pathname.split('/').slice(0,-1).join('/');
appConfig.ui.fqdn = appConfig.ui.protocol + '://' + appConfig.ui.host;

// Set the API config using the UI config
switch(appConfig.ui.name) {
    case 'localhost':
        appConfig.api.protocol = appConfig.ui.protocol;
        appConfig.api.host = 'localhost';
        appConfig.api.port = ${API_PORT};
        appConfig.api.fqdn = appConfig.api.protocol + '://' + appConfig.api.host + ':' + appConfig.api.port;
        break;
    default:
        appConfig.api.protocol = appConfig.ui.protocol;
        appConfig.api.host = 'api.' + appConfig.ui.host;
        appConfig.api.port = ${API_PORT};
        appConfig.api.fqdn = appConfig.api.protocol + '://' + appConfig.api.host;
        break;
}

// Service Worker & Cache settings
appConfig.useServiceWorker = ${USE_SERVICE_WORKER:-true};
appConfig.useAppCache = ${USE_APP_CACHE:-true};
appConfig.useDataCache = ${USE_DATA_CACHE:-true};
appConfig.useTileCache = ${USE_TILE_CACHE:-true};
appConfig.fetchTimeout = 5000;

console.log('config.js=>appConfig', appConfig);
"

# =============================================================================
# Generate file
# =============================================================================

CONFIG_FILE="$BASE_PATH/js/config.js"
if [ -d "$(dirname "$CONFIG_FILE")" ]; then
    echo "$CONFIG_CONTENT" > "$CONFIG_FILE"
    echo "Generated: $CONFIG_FILE"
else
    echo "SKIP: Directory not found - $(dirname "$CONFIG_FILE")"
fi

echo ""
echo "Done."

# If not local mode and there are remaining args, exec them (Docker entrypoint behavior)
if [ "$LOCAL_MODE" = false ] && [ $# -gt 0 ]; then
    exec "$@"
fi
