/*
  build_normalize_sql.js — emit the data-cleanup half of migration 023.

  Rather than hand-writing UPDATE statements from a one-off look at the data,
  this reads every DISTINCT value actually present in each controlled-vocabulary
  column, runs it through the same _helpers/normalize_values.js the ingest path
  uses, and emits an UPDATE only where the two disagree. The cleanup and the
  guard against new bad data are therefore the same rule expressed once.

  Values the normaliser does not recognise are reported as comments rather than
  rewritten. Guessing at an unanticipated answer is worse than leaving it for a
  human, and schema.test.js will keep surfacing it.

      docker exec api_vp node /opt/api/_schema/build_normalize_sql.js [extra.json]

  The optional argument is a JSON file of {field: {value: count}} gathered from
  ANOTHER database, merged into the values read locally. It exists because dev
  and prod diverge: prod carries multi-member substrate arrays, an
  'Associated with wetland complex' pool type and 55 rows of a bare 'Ephemeral'
  inlet that dev has never seen. A migration generated from dev alone would run
  clean on prod and leave all of it behind.
*/

require('rootpath')();
const { query } = require('_helpers/db_postgres');
const { VOCABULARIES, normalizeField, isCanonical } = require('_helpers/normalize_values');

const q = s => "'" + String(s).replace(/'/g, "''") + "'";

(async () => {
    // Values observed in another environment, merged with what is here.
    const extraPath = process.argv[2];
    const extra = extraPath ? JSON.parse(require('fs').readFileSync(extraPath, 'utf8')) : {};

    const out = [];
    const unrecognised = [];

    /*
      Format-only cleanup, emitted first and unconditionally.

      A JSON-array wrapper is a storage defect regardless of what is inside it.
      The vocabulary pass below deliberately skips values it cannot resolve --
      but that left '["Artificial"]' wrapped on production, because "Artificial"
      is not a pool type anyone has decided on yet. Unwrapping is not a guess and
      must not wait on one.
    */
    out.push('-- ── JSON-array unwrapping (format only, independent of vocabulary) ────────');
    for (const field of Object.keys(VOCABULARIES)) {
        const res = await query(
            `SELECT count(*) AS n FROM vpvisit WHERE "${field}" ~ '^\\s*\\['`);
        const local = Number(res.rows[0].n);
        const elsewhere = Object.entries(extra[field] || {})
            .filter(([v]) => /^\s*\[/.test(v)).length;
        if (!local && !elsewhere) continue;
        out.push(`UPDATE vpvisit SET "${field}" = btrim(regexp_replace("${field}", '[\\[\\]"]', '', 'g'))`);
        out.push(`  WHERE "${field}" ~ '^\\s*\\[';  -- ${local} row(s) here${elsewhere ? `, ${elsewhere} distinct value(s) elsewhere` : ''}`);
    }
    out.push('');

    out.push('-- ── Controlled vocabulary cleanup ─────────────────────────────────────────');
    out.push('-- Generated by _schema/build_normalize_sql.js from the values actually present');
    out.push('-- in the database, resolved through _helpers/normalize_values.js.');
    out.push('');

    for (const field of Object.keys(VOCABULARIES)) {
        const res = await query(
            `SELECT DISTINCT "${field}" AS v, count(*) AS n FROM vpvisit WHERE "${field}" IS NOT NULL GROUP BY 1`);
        const rows = res.rows.slice();
        for (const [v, n] of Object.entries(extra[field] || {})) {
            if (!rows.some(r => r.v === v)) rows.push({ v, n: `${n}, elsewhere` });
        }
        const changes = [];
        for (const row of rows) {
            const before = row.v;
            const after = normalizeField(field, before);
            if (after === before) continue;
            if (after !== null && !isCanonical(field, after)) {
                unrecognised.push(`${field}: ${JSON.stringify(before)} (${row.n} rows)`);
                continue;
            }
            changes.push({ before, after, n: row.n });
        }
        if (!changes.length) continue;

        out.push(`-- ${field}`);
        for (const c of changes) {
            const target = c.after === null ? 'NULL' : q(c.after);
            out.push(`UPDATE vpvisit SET "${field}" = ${target} WHERE "${field}" = ${q(c.before)};`
                     + `  -- ${c.n} row${c.n === '1' ? '' : 's'}`);
        }
        out.push('');
    }

    // Values present that the vocabulary does not cover at all.
    for (const field of Object.keys(VOCABULARIES)) {
        const res = await query(
            `SELECT "${field}" AS v, count(*) AS n FROM vpvisit WHERE "${field}" IS NOT NULL GROUP BY 1`);
        const merged = res.rows.concat(
            Object.entries(extra[field] || {})
                  .filter(([v]) => !res.rows.some(r => r.v === v))
                  .map(([v, n]) => ({ v, n: `${n}, elsewhere` })));
        for (const row of merged) {
            const after = normalizeField(field, row.v);
            if (after !== null && !isCanonical(field, after)) {
                const line = `${field} = ${JSON.stringify(row.v)} (${row.n} rows)`;
                if (!unrecognised.includes(line)) unrecognised.push(line);
            }
        }
    }

    if (unrecognised.length) {
        out.push('-- Values left untouched because no canonical spelling covers them. Each needs');
        out.push('-- a human decision; none is rewritten here, and schema.test.js reports them.');
        for (const u of [...new Set(unrecognised)]) out.push(`--   ${u}`);
        out.push('');
    }

    process.stdout.write(out.join('\n'));
    process.exit(0);
})().catch(e => { console.error(e.message); process.exit(1); });
